/*
 * Copyright © Bart Kampers
 */
package bka.communication.graph;

import bka.communication.json.*;
import java.util.logging.*;
import org.json.*;

/**
 *
 * @author bartk
 */
public class JsonTerminal extends bka.graph.swing.AbstractEditPanel {


    public JsonTerminal(TerminalVertex terminalVertex) {
        this.terminalVertex = terminalVertex;
        initComponents();
        receiverThread = new Thread(new ReceiverTask());
    }


    @Override
    public void confirm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        sendPanel = new javax.swing.JPanel();
        sendScrollPane = new javax.swing.JScrollPane();
        sendTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        receivePanel = new javax.swing.JPanel();
        receiveScrollPane = new javax.swing.JScrollPane();
        receiveTextArea = new javax.swing.JTextArea();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(0.5);

        sendTextArea.setColumns(20);
        sendTextArea.setRows(5);
        sendScrollPane.setViewportView(sendTextArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButton_actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sendPanelLayout = new javax.swing.GroupLayout(sendPanel);
        sendPanel.setLayout(sendPanelLayout);
        sendPanelLayout.setHorizontalGroup(
            sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendPanelLayout.createSequentialGroup()
                .addComponent(sendButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        sendPanelLayout.setVerticalGroup(
            sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton))
        );

        splitPane.setTopComponent(sendPanel);

        receiveTextArea.setEditable(false);
        receiveTextArea.setColumns(20);
        receiveTextArea.setRows(5);
        receiveScrollPane.setViewportView(receiveTextArea);

        javax.swing.GroupLayout receivePanelLayout = new javax.swing.GroupLayout(receivePanel);
        receivePanel.setLayout(receivePanelLayout);
        receivePanelLayout.setHorizontalGroup(
            receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receiveScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        receivePanelLayout.setVerticalGroup(
            receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receiveScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPane.setRightComponent(receivePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void sendButton_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButton_actionPerformed
        try {
            JSONObject message = new JSONObject(sendTextArea.getText());
            if (! receiverThread.isAlive()) {
                receiverThread.start();
            }
            Transporter transporter = getTransporter();
            if (transporter != null) {
                transporter.send(message);
            }
        }
        catch (JSONException ex) {
            receiveTextArea.setText(ex.getMessage());
        }
    }//GEN-LAST:event_sendButton_actionPerformed


    private Transporter getTransporter() {
        return (terminalVertex != null) ? terminalVertex.getTransporter() : null;
    }


    private boolean transporterAvailable() {
        return getTransporter() != null;
    }


    private class ReceiverTask implements Runnable {

        @Override
        public void run() {
            while (transporterAvailable()) {
                try {
                    JSONObject received = getTransporter().nextReceivedObject();
                    receiveTextArea.setText(received.toString(2));
                }
                catch (InterruptedException | JSONException ex) {
                    Logger.getLogger(JsonTerminal.class.getName()).log(Level.WARNING, null, ex);
                }
            }
        }

    }


    private final TerminalVertex terminalVertex;
    private final Thread receiverThread;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel receivePanel;
    private javax.swing.JScrollPane receiveScrollPane;
    private javax.swing.JTextArea receiveTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JPanel sendPanel;
    private javax.swing.JScrollPane sendScrollPane;
    private javax.swing.JTextArea sendTextArea;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

}
